# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: xcodebuild -scheme WeeklyChallenges2023Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16 Plus,OS=18.0' build
    - name: Run tests
      run: xcodebuild -scheme WeeklyChallenges2023Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16 Plus,OS=18.0' test
